---
- name: Playbook for upgrading the Junos Routers
  hosts: all
  connection: local
  gather_facts: no
  roles:
    - Juniper.junos 
  vars_prompt:
    - name: juniper_junos_facts_config_format
      prompt: "Please enter ther format for the device configuration(xml, json, set, text): "
      default: xml      
  tasks:
#    - import_tasks: tasks/gather_facts_without_config.yml
#    - import_tasks: tasks/abort_if_1_RE.yml
#    - import_tasks: tasks/show_gathered_config.yml 
    - import_tasks: tasks/jsnapy_tests_generator/validate_interface_status.yml

    - name: Test against the conditions only
      juniper_junos_jsnapy:
        action: "snapcheck"
        test_files: jsnapy_tests/validations/validate_interface_admin_status.yml
"        test_files: jsnapy_tests/show_gbp_summary.yml
