---
- name: Abort if any only single RE
#  fail:
#    msg: "Only 1 Routing engine found. Aborting the software upgrade for device {{ inventory_hostname }}."
  meta:
    free_form: end_play
  when: not ansible_facts.junos.has_2RE
